services:
  - type: web
    name: cerensafe
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --timeout 120 server:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
